# Generated by Django 5.2.3 on 2025-11-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ic',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BinaryField(),
        ),
    ]
