# Generated by Django 5.2.8 on 2025-12-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='assigned_doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='DoctorUser',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
